### ISSUE TITLE
Pulseaudio is a hard dependency.

### ISSUE THREAD

**Issue by orbea** [i3/i3status#101]
When compiling i3status without pulseaudio installed I arrived upon this horrible reality.
```
 CC src/print_cpu_temperature.c
 CC src/auto_detect_format.c
 CC src/print_path_exists.c
 CC src/print_disk_info.c
 CC src/print_eth_info.c
 CC src/print_cpu_usage.c
 CC src/print_battery_info.c
src/pulse.c:5:30: fatal error: pulse/pulseaudio.h: No such file or directory
compilation terminated
```
Here is a patch that fixes this misstep which I can confirm works with i3status 2.10.
http://pastebin.com/i2VnRmcK

Please do not force users to choose between using pulse and finding a replacement for i3status and/or i3 itself.  The latter option will certainly win in my case.

Lastly I know this is a repeat issue, however the issue still persists so I feel I am unfortunately left no choice other than to make a new issue...  Please do not close it without resolving the issue by either making pulseaudio an optional dependency or by not using it at all.

**Comment by Airblader** [comment]
As explained in the pull request, we don't force you to use pulse. We force you to have libpulse in memory. What your system uses is still up to you. This is just like with libiw as Michael explained there as well.

**Comment by stapelberg** [comment]
duplicate of #43
